# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-Magic
version:      2.00
version_from: lib/Text/Magic.pm
installdirs:  site
distribution_type: module
generated_by: manual
